### ISSUE TITLE
Black screen and null wakeupWord

### ISSUE THREAD

**Issue by lcarnevale** [ROBOTEAM-HOME/temi-welcomingmode-b2b#15]
Hello all,

I have started this application encountering an issue. 
Setting up the Kiosk mode, the screen becomes black; moreover, when I click the tablet, I see this exception into Logcat:

```
11-27 15:18:37.902 17257-17257/com.robotemi.welcomingbtob E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.robotemi.welcomingbtob, PID: 17257
    java.lang.IllegalStateException: it.wakeupWord must not be null
        at com.robotemi.sdk.Robot.getWakeupWord()
        at com.robotemi.welcomingbtob.tips.TipsViewImpl.loadTips(TipsViewImpl.kt:45)
        at com.robotemi.welcomingbtob.tips.TipsViewImpl.onWindowFocusChanged(TipsViewImpl.kt:56)
        at com.robotemi.welcomingbtob.tips.TipsViewImpl.start(TipsViewImpl.kt:88)
        at com.robotemi.welcomingbtob.featurelist.FeatureBaseFragment.onResume(FeatureBaseFragment.kt:71)
        at androidx.fragment.app.Fragment.performResume(Fragment.java:2649)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:922)
        at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1238)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1303)
        at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:439)
        at androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManagerImpl.java:2079)
        at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:1869)
        at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManagerImpl.java:1824)
        at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManagerImpl.java:1727)
        at androidx.fragment.app.FragmentManagerImpl$2.run(FragmentManagerImpl.java:150)
        at android.os.Handler.handleCallback(Handler.java:743)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5417)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:772)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:662)
```

Best,
Lorenzo.

**Comment by lcgao** [comment]
Fixed in latest temi SDK
